config/routes.rb
Rails.application.routes.draw do
  resources :groups

  resources :assignments

  resources :tasks
  post 'mark_done' => 'tasks#mark_done'

  resources :users

  root :to => 'sessions#new'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :memberships, only: [:new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

  resources :user_assignments

  get 'welcome', to: 'welcome#index'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :members, :through => :memberships, source: :user

  validates :name, presence: true, allow_blank: false,
            length: {minimum: 1, maximum: 18}
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_user_is_signed_in

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @membership = Membership.new
    @membership.group = @group
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        m = Membership.create(user_id: current_user, group_id: @group.id)
        current_user.memberships << m
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= bootstrap_form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :name , placeholder: 'Name of the group'%>
    <%= f.text_area :description, placeholder: 'Description of the group' %>
    <%= f.submit%>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-body" id="group_index">
<h1 class="panel-heading"><i class="fa fa-trello fa-2x" > Groups </i></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group%></td>
        <td><%= group.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_group_path do %>
  <i class='fa fa-users btn btn-default'> New Group</i>
<% end %>
</div>

app/views/groups/new.html.erb
<div class="container-fluid col-md-6 col-md-offset-3" id="newgroup_form">
<h1>New Group</h1>

<%= render 'form' %>

</div>

app/views/groups/show.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-body" id="group_show">
<h1 class="panel-heading">
  <i class="fa fa-trello fa-2x">
    <%= @group.name %>
  </i>
</h1>

<p class="lead ">
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>Users:</strong>
        <table class="table table-hover">
          <tbody>
          <% @group.members.each do |member| %>
              <tr>
                <td><%= link_to member.name, member %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
</p>
<% if Membership.membership_exists?(current_user.id, @group.id) %>
  <%= link_to 'Leave the group', membership_path(Membership.find_mem(current_user, @group.id)), method: :delete, class:'btn btn-warning' %>
  <%= link_to 'Destroy group', @group, method: :delete, class:'btn btn-danger'%>
<% else %>
  <%= form_for(@membership, method: :post) do |f| %>
    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>
    <div class="field">
      <%= f.hidden_field :group_id, :value => @group.id %>
    </div>
    <div class="actions">
      <%= button_tag(type: 'submit', class: 'btn btn-primary') do %>
        <i class='fa fa-users'> Join the club </i>
      <% end %>
    </div>
  <% end %>
<% end %>
<br/>
</div>