config/routes.rb
Rails.application.routes.draw do
  resources :groups

  resources :assignments

  resources :tasks
  post 'mark_done' => 'tasks#mark_done'

  resources :users

  root :to => 'sessions#new'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :memberships, only: [:new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

  resources :user_assignments

  get 'welcome', to: 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  #group
  has_many :memberships
  has_many :groups, :through => :memberships

  #assignments
  has_many :user_assignments
  has_many :assignments, :through => :user_assignments
  has_many :tasks, :through => :assignments

  #passwrd
  has_secure_password

  validates :name, uniqueness: true
  validates :name, length: {minimum: 3,
                            maximum: 15}
  validates_format_of :password, :with => /(?=.*\d)(?=.*([A-Z]))/
  validates :password, length: {minimum: 4}

  #scopes

  scope :all_except, ->(user) { where.not(id: user) } #returns all except parameter user

  def to_s
    self.name
  end

  def get_created_assignments
    Assignment.where(creator_id: self.id)
  end

  private
  def self.all_except(user)
    where.not(id: user)
  end

  def self.all_who_are_in_same_group_as_creator(current_user)
    group_ids = current_user.groups.map{|g| g.id}
    user_ids = Membership.where(group_id: group_ids).map{|u| u.user_id}
    user_ids = user_ids - [current_user.id] unless user_ids.empty?
    User.where(id: user_ids)
  end

  def self.all_in_same_group_but_not_assigned_to_assignment(assignment_id, current_user)
      in_same_group = all_who_are_in_same_group_as_creator(current_user)
      in_same_group.select {|m| m.assignments.find_by_id(assignment_id).nil?}
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_user_is_signed_in, except: [:new, :create]
  before_action :ensure_rights, only: [:show, :edit]


  # GET /users
  # GET /users.json
  def index
    @users = User.all.includes(:groups).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }

      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :birthdate, :password, :password_confirmation)
    end

    def ensure_rights

      if not current_user.id === @user.id
        redirect_to :back, alert: "You don't have right permissions to view other profiles"
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_assigned_to_assignments.html.erb
<div class="panel-body">
  <div class="panel-heading">
<h3>Assigned to assignments</h3>
  </div>
<table class="table">


  <tbody>
  <% @user.assignments.each do |assignment| %>
      <tr>
        <td><%= link_to assignment.name, assignment %></td>
        <% if assignment.is_ready%>
            <td>The assignment is ready and the creator can now destroy it.</td>
        <% elsif assignment.tasks.empty?%>
        <td>This assignment doesn't have any tasks yet.</td>
        <% else %>
            <td>Assignment is not fully ready yet.</td>
        <% end %>

        <td>

          <%if not assignment.tasks.empty? %>
          <table class="table borderless">
            <thead>
            <th>Tasks</th>
            <th></th>
            <th></th>
            <th></th>
            </thead>
            <tbody>
            <% assignment.tasks.each do |task| %>
                <tr>
                  <td><%=link_to task.name, task%></td>
                  <% if task.is_done %>
                  <td>Ready</td>
                      <% else %>
                  <td></td>
                      <% end %>
                  <td><%= task.description %></td>
                  <td><%=button_to "Mark as done", mark_done_path(:id => task.id), method: :post, class:'btn btn-primary' if not task.is_done%></td>
                </tr>
            <% end %>
            <td><br></td>
            </tbody>
          </table>
            <% end%>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/_creator_of.html.erb
<div class="panel-body">
  <div class="panel-heading">
<h3>Creator of</h3>
  </div>


<table class="table borderless">


  <tbody>
  <% @user.get_created_assignments.each do |assignment| %>
      <tr>
        <td><%= link_to assignment.name, assignment %></td>
        <% if assignment.is_done %>
            <td><%= link_to 'Mark permanently done', assignment, method: :delete, data: {confirm: 'This item can be removed now. Are you sure?'}, class:'btn btn-danger'%></td>
        <% else %>
            <td></td>
        <%end %>
        <td>
          <% if current_user.id == @user.id and not User.all_in_same_group_but_not_assigned_to_assignment(assignment.id, current_user).empty? %>
            <%= link_to new_user_assignment_path(:assignment_id => assignment.id) do %>
              <i class="fa fa-user-plus btn btn-info">  Add worker</i>
            <% end %>
          <% else %>
              <i>All workers already assigned to this</i>
          <% end %>
        </td>
        <td>
          <% if current_user.id == assignment.creator_id%>
            <%= link_to new_task_path(:assignment_id => assignment.id) do %>
            <i class="fa fa-tasks btn btn-primary">  New task</i> 
            <% end %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/_form.html.erb
<%=  bootstrap_form_for(@user) do |f|%>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


        <%= f.text_field :name , icon:"user", placeholder:"Username"%>
        <div id="newuser_dateselect">
        <%= f.date_select :birthdate, :start_year => Time.now.year - 60, :end_year => Time.now.year, label: 'Date of birth'%>
        </div>

      <%= f.password_field :password , icon:"lock",  placeholder:"Password with one numeral and one uppercase"%>
      <%= f.password_field :password_confirmation, icon:"eye-open", placeholder: "Match with the typed password" %>

    <%= f.submit%>
<% end %>

app/views/users/_joined_organizations.html.erb
<div class="panel-body">
  <div class="panel-heading">
    <h3>Joined organizations </h3>
  </div>
<% @user.groups.each do |group| %>
        <ul>
          <li><%= link_to group.name, group %></li>
        </ul>
<% end %>
</div>

app/views/users/edit.html.erb
<div class="col-md-6 col-md-offset-3" id="editfield">
<h1>Editing <%= link_to @user.name, @user%></h1>


<%= render 'form' %>


</div>

app/views/users/index.html.erb
<div class="col-md-4 col-md-offset-4 panel panel-body" id="usershow_index">

<h1 class="panel-heading"><i class="fa fa-trello fa-2x">  Users</i></h1>


<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Joined groups</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td>
          <table class="">
            <tbody>

            <% user.groups.each do |group| %>
                <ul>
                    <li><%=link_to group.name, group%></li>
                </ul>
            <%end%>

            </tbody>
          </table>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

app/views/users/new.html.erb
<div class="col-md-6 col-md-offset-3" >
    <div class="container-fluid" id="newuser_field">
    <%= render 'form' %>
    </div>
</div>

app/views/users/show.html.erb
<script>

    $(document).ready(function() {

        // page is now ready, initialize the calendar...

        var calendar = $('#calendar');

        calendar.fullCalendar({
            // put your options and callbacks here
            lang: 'fi',
            events: '/assignments.json',
            firstDay: 1,
            eventTextColor: "white"


            // Need more adjusting

        });

    });

</script>

<div class="container-fluid">
    <div id="userbody_form">
      <div class="col-md-2 col-md-offset-10">
            <h1>
              <%= @user.name %>
            </h1>

          <%= link_to  edit_user_path(@user) do %>
              <i class="fa fa-pencil-square-o btn btn-default"> Edit your information</i>  <!--class:'btn btn-default' %> -->
          <% end %>

    </div>


    <div class="col-md-6" id="calendar"></div>

          <div class="workbox">

                <div id="inline-custom-box" class="col-md-6 panel panel-default">
                  <%= render 'joined_organizations' %>
                </div>

                <div id="inline-custom-box" class="col-md-6 panel panel-default">
                 <%= render 'creator_of' %>
                </div>

                <div id="inline-custom-box" class="col-md-6 panel panel-default">
                  <%= render 'assigned_to_assignments' %>
                </div>
          </div>
    </div>
</div>