config/routes.rb
Rails.application.routes.draw do
  resources :groups

  resources :assignments

  resources :tasks
  post 'mark_done' => 'tasks#mark_done'

  resources :users

  root :to => 'sessions#new'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :memberships, only: [:new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

  resources :user_assignments

  get 'welcome', to: 'welcome#index'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
        <%= render 'layouts/navigation_links' %>
      </ul>



      <div class="nav navbar-nav navbar-right">
        <li><%= link_to 'Sign up', signup_path if not current_user%></li>
        <li><%= link_to 'Sign in', signin_path if not current_user%></li>
        <li><%= link_to 'Sign out', signout_path, method: :delete, icon:'user'  if current_user%></li>
      </div>

    </div>

  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if current_user %>

    <li><%=link_to current_user, current_user %></li>
    <li><%=link_to 'Users', users_path%></li>  
    <li><%=link_to 'Assignments', assignments_path%></li>  
    <li><%=link_to 'Create assignment', new_assignment_path%></li>
    <li><%=link_to 'Groups', groups_path%></li>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Scheduler" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Scheduler" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>

  <main role="main" class=".container">
    <%= render 'layouts/messages' %>

    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>

  </main>
  </body>
</html>

app/views/layouts/application.old.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scheduler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


    <nav>
        <% if current_user %>
        <%=link_to 'users', users_path%> | 
        <%=link_to 'assignments', assignments_path%> | 
          <%= link_to 'create assignment', new_assignment_path%> |
        <%=link_to 'groups', groups_path%> <b>|</b>
            [<%= link_to current_user.name, current_user %>]
    <%end%>

<%= link_to 'sign up', signup_path if not current_user%> |
<%= link_to 'sign in', signin_path if not current_user%> |
      <%= link_to 'sign with facebook', "facebook" if not current_user%> |
<%= link_to 'sign out', signout_path, method: :delete  if current_user%>
    </nav>

<%= yield %>


</body>
</html>